### ISSUE TITLE
Add support for 0.8 protocol

### ISSUE THREAD

**Issue by bpot** [acrosa/kafka-rb#16]
Kafka 0.8 makes backwards-incompatible changes to the protocol.

I'm planning to start tackling the changes necessary to support 0.8.  This includes supporting the metadata api and making a "smart" producer that has behavior equivalent to the scala producer.

Has anyone started down this path yet? I don't want to duplicate work.

My plan is to have the gem no longer support 0.7's protocol and bump the gems major? version so that the 0.x series can continue to be released with 0.7 support as long as people are still running the 0.7 series of the server.  Does this seem reasonable?

**Comment by aviflax** [comment]
It would be great to update the readme to make clear that this lib only supports Kafka 0.7 or lower and to link to poseidon for 0.8 and up.

**Comment by acrosa** [comment]
It would be great if you could send a pull request with it too :)
I don't maintain this anymore.

**Comment by aviflax** [comment]
You got it! Created #28.

**Comment by acrosa** [comment]
Merged from the bus! Thanks

**Comment by aviflax** [comment]
My pleasure!
